#
# test-kitchen using kitchen-dokken
#
# to use this instead of Vagrant, use:
#
#   $ KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify
#
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  # chef_version: 12.19.36

transport:
  name: dokken

provisioner:
  name: dokken
  # chef_log_level: debug

platforms:
#- name: debian-9
#  driver:
#    image: debian:9
#    pid_one_command: /bin/systemd
#    intermediate_instructions:
#      - RUN /usr/bin/apt-get update
#      - RUN /usr/bin/apt-get install systemd -y
#      - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

- name: debian-8
  driver:
    image: debian:8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

# comment this out, if Debian 7 is not needed
#- name: debian-7
#  driver:
#    image: debian:7
#    intermediate_instructions:
#      - RUN /usr/bin/apt-get update
#      - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

# suites are taken from .kitchen.yml usually
# suites:
