driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  intermediate_instructions:
    - RUN /usr/bin/apt-get update
    - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y

transport:
  name: dokken

provisioner:
  name: dokken

platforms:
- name: debian-8
  driver:
    image: debian:8
    pid_one_command: /bin/systemd
