#
# test-kitchen using kitchen-dokken
#
# to use this instead of Vagrant, use:
#
#   $ KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen verify
#
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: 12.21.3

transport:
  name: dokken

provisioner:
  name: dokken
  # chef_log_level: debug

platforms:
- name: debian-9
  driver:
    image: debian:9
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update
      - RUN /usr/bin/apt-get install systemd -y
      - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools gnupg -y
  run_list:
  - recipe[fix-ipv6-kitchen-dokken::default]

# suites are taken from .kitchen.yml usually
# suites:
