---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  name: chef_zero

platforms:
  - name: debian-8.2

suites:
  - name: default
    run_list:
      - recipe[site_t3chefjenkins_dev::default]
    attributes:
    driver_config:
      network:
      - ["private_network", {ip: "192.168.88.23"}]
